# Calling the Numpy directory 

In [2]:
import numpy as np

# Creating a 5 element array

In [3]:
myFavorites = np.array([8, 6, 7, 5, 3])

# Performing the 5 Aggregate Functions on myFavorites

In [4]:
myFavorites.max()

8

In [5]:
myFavorites.min()

3

In [7]:
myFavorites.mean()

5.8

In [8]:
myFavorites.std()

1.7204650534085253

In [9]:
myFavorites.sum()

29

# Creating a 5 Element Array of Only Ones

In [10]:
OneArrayToRuleThemAll = np.ones(5)

# Adding myFavorites to OneArrayToRuleThemAll

In [11]:
myFavorites + OneArrayToRuleThemAll

array([9., 7., 8., 6., 4.])

# Multiplying every element in myFavorites by two

In [12]:
myFavorites * 2

array([16, 12, 14, 10,  6])

# Calling the Third Element of myFavorites Using Indexing

In [13]:
myFavorites[2]

7

# Create a four element, two-by-two matrix of numbers named TheMatrixHasYou

In [16]:
TheMatrixHasYou = np.array([[0,9],[2,3]])

# Access the upper left element in TheMatrixHasYou using indexing.

In [17]:
TheMatrixHasYou[0,0]

0

# Find the largest number in each row for TheMatrixHasYou

In [18]:
TheMatrixHasYou.max(axis = 1)

array([9, 3])

# Reshape TheMatrixHasYou into a matrix with one row and four columns.

In [19]:
TheMatrixHasYou.reshape(1,4)

array([[0, 9, 2, 3]])